Topic list implementation ported to API
HuCaresTeam/schedulearn pull request #19
Opened 2020-05-06 18:07 UTC by AinoraZ

- Ported topic list implementation to Controller API.
- Added functionality to get single topic by id.
- Added functionality to get parent of topic by id.
- Added functionality to modify topic name/description.

2020-05-06 18:38 UTC, DominykasP requested changes

2020-05-06 18:38 UTC, DominykasP commented on SchedulearnBackend/SchedulearnBackend/Controllers/TopicController.cs
> +            System.Diagnostics.Debug.WriteLine($"GetTopic {id}");
`GetTopic` in WriteLine should be renamed to `GetParentTopic`

2020-05-06 18:38 UTC, DominykasP commented on SchedulearnBackend/SchedulearnBackend/Services/TopicService.cs
> +            return rootTopic ?? throw new NotFoundException("Root topic does not exist");
Are two checks for null necessary?

2020-05-06 19:44 UTC, DominykasP approved these changes

2020-05-06 19:46 UTC, merged

2020-05-11 10:31 UTC, AinoraZ commented
![](https://github.trello.services/images/mini-trello-icon.png) [Dotnetify rewrite to REST api](https://trello.com/c/JktKkaWe/1-dotnetify-rewrite-to-rest-api)