Pjuvis topics by team
HuCaresTeam/schedulearn pull request #24
Opened 2020-05-08 21:45 UTC by DominykasP

Pjūvis What topics have been and will be learned for selected team can be access from `api/Team/{id}/topics`
Pjūvis Which teams learned a selected topic can be accessed from `api/Topic/{topicId}/teams/{baseTeamId}`

2020-05-08 21:46 UTC, DominykasP commented on SchedulearnBackend/SchedulearnBackend/Services/LearningDayService.cs
> -            await _userService.GetUserAsync(learningDayToCreate.UserId); //Check user exists
Got circular dependency here: UserService -> TeamService -> LearningDayService -> UserService.

2020-05-10 09:24 UTC, AinoraZ requested changes

2020-05-10 09:24 UTC, AinoraZ commented on SchedulearnBackend/SchedulearnBackend/Controllers/TeamController.cs
> +        public async Task<ActionResult<IEnumerable<TeamTopics>>> GetTopicsByTeam(int id)
Perhaps move this to Topic controller?

2020-05-10 09:24 UTC, AinoraZ commented on SchedulearnBackend/SchedulearnBackend/Controllers/DTOs/Topic/TeamTopics.cs
> +        public string ManagerName { get; set; }
Could add ManagerId in case we need to query manager.

2020-05-10 09:24 UTC, AinoraZ commented on SchedulearnBackend/SchedulearnBackend/Controllers/TeamController.cs
> +        public async Task<ActionResult<IEnumerable<TeamTopics>>> GetTopicsByTeam(int id)
Perhaps it would be more clear to get these topics by manager id, as in, get all topics from all teams managed by this manager. GetTopicsByManager

2020-05-10 09:24 UTC, AinoraZ commented on SchedulearnBackend/SchedulearnBackend/Controllers/TeamController.cs
> +        public async Task<ActionResult<IEnumerable<TeamTopics>>> GetTopicsByTeam(int id)
Add extra controller endpoint, that would get topics by ONE team id (no accessible teams)

2020-05-10 13:00 UTC, AinoraZ approved these changes

2020-05-10 13:01 UTC, merged