Added support for My Limits view in fornt-end and back-end
HuCaresTeam/schedulearn pull request #33
Opened 2020-05-10 20:25 UTC by MartynasBas

Added My Limits functionality to front-end and back-end

2020-05-10 20:31 UTC, AinoraZ requested changes

2020-05-10 20:31 UTC, AinoraZ commented on SchedulearnBackend/SchedulearnBackend/Controllers/LimitController.cs
> +
Excesive whitespace

2020-05-10 20:31 UTC, AinoraZ commented on schedulearn-frontend/src/App.tsx
> +                <AnalyzeData />
Excesive whitespace

2020-05-10 20:32 UTC, DominykasP requested changes

2020-05-10 20:32 UTC, DominykasP commented on schedulearn-frontend/src/server-components/LimitViewer.tsx
> +      throw new Error("Should never reach this calendar when not logged in");
Fix error message

2020-05-10 20:45 UTC, DominykasP approved these changes
🥇

2020-05-10 20:50 UTC, AinoraZ approved these changes

2020-05-10 20:50 UTC, merged

2020-05-11 10:29 UTC, AinoraZ commented
![](https://github.trello.services/images/mini-trello-icon.png) [My limits page](https://trello.com/c/Y755QLZM/4-my-limits-page)