Added TopicsByManagerView
HuCaresTeam/schedulearn pull request #35
Opened 2020-05-10 21:30 UTC by DominykasP

2020-05-10 21:33 UTC, AinoraZ requested changes

2020-05-10 21:33 UTC, AinoraZ commented on schedulearn-frontend/src/server-components/Views/TopicsByManagerView.tsx
> +      (<FlatTopicList topics={this.state.topics} />) : undefined;
Perhaps it would be better to just pass an empty list, as such (this.state.topics ?? [])

2020-05-10 21:33 UTC, AinoraZ commented on schedulearn-frontend/src/server-components/Views/TopicsByManagerView.tsx
> +    console.log("Paspaude " + teamId);
Remove

2020-05-10 21:47 UTC, AinoraZ approved these changes

2020-05-10 21:49 UTC, MartynasBas approved these changes
LGTM

2020-05-10 21:49 UTC, merged

2020-05-11 10:27 UTC, AinoraZ commented
![](https://github.trello.services/images/mini-trello-icon.png) [Pjūvis - what topics have been and will be learned for current managers all accessible teams - frontend](https://trello.com/c/M09pSKIc/20-pj%C5%ABvis-what-topics-have-been-and-will-be-learned-for-current-managers-all-accessible-teams-frontend)