Added concurency resolver modal
HuCaresTeam/schedulearn pull request #68
Opened 2020-05-28 23:20 UTC by AinoraZ

2020-05-28 23:25 UTC, DominykasP requested changes

2020-05-28 23:25 UTC, DominykasP commented on schedulearn-frontend/src/server-components/UserLearningDayCalendar.tsx
> +    }).then(() => this.fetchUserLearningDays(), () => this.openConcurencyResolver(learningDayEvent));
Should check what type of error it is.

2020-05-28 23:38 UTC, DominykasP approved these changes

2020-05-28 23:39 UTC, merged

2020-05-29 01:17 UTC, AinoraZ commented
![](https://github.trello.services/images/mini-trello-icon.png) [Optimistic locking modal](https://trello.com/c/bCW71kc3/7-optimistic-locking-modal)